name: 'Pubspec version bumper'
description: 'Bump the version of a pubspec file'
author: 'Ricardo Dalarme'

inputs:
  mode:
    description: 'major|minor|patch'
    required: true
  consider_code:
    description: 'Consider the code as a version'
    default: 'false'

outputs:
  new_version:
    description: 'The bumped version'

runs:
  using: 'node20'
  main: 'dist/index.js'
